//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TJS.VehicleTracker.PL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVehicle
    {
        public System.Guid Id { get; set; }
        public System.Guid ColorId { get; set; }
        public System.Guid MakeId { get; set; }
        public System.Guid ModelId { get; set; }
        public string VIN { get; set; }
        public int Year { get; set; }
    }
}
